name: Синхронизация с Яндекс Диском
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Загрузить файл на Яндекс Диск
        env:
          YANDEX_TOKEN: ${{ secrets.YANDEX_TOKEN }}
        run: |
          FILE_URL="https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/WHITE-CIDR-RU-all.txt"
          DISK_PATH="disk:/git_sinc/WHITE-CIDR-RU-all.txt"
          
          # Отправляем данные как обычную форму (application/x-www-form-urlencoded)
          curl -X POST \
            -H "Authorization: OAuth $YANDEX_TOKEN" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            --data-urlencode "url=$FILE_URL" \
            --data-urlencode "path=$DISK_PATH" \
            "https://cloud-api.yandex.net/v1/disk/resources/upload"
